DELETE FROM payments;
DELETE FROM rentals;
DELETE FROM users_roles;
DELETE FROM users;
DELETE FROM roles;
DELETE FROM cars;

ALTER TABLE cars AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
