name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      TELEGRAM_BOT_NAME: ${{secrets.TELEGRAM_BOT_NAME}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
